/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hotel;


import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;

/**
 *
 * @author mz
 */
public class UserFram extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserFram.class.getName());
    private UserManager userManager;

    private HashMap<Integer, Customers> customers ;
    private RoomServiceManager roomManger;
    private HashMap<Integer, Room> rooms;
    private HashMap<Integer,Service> services;
    private void loadRoomsToTable() {
        DefaultTableModel model = (DefaultTableModel) RoomTable2.getModel();
        model.setRowCount(0);
        for (Room room : rooms.values()) {
            model.addRow(new Object[]{
                    room.getRoomId(),
                    room.getRoomType(),
                    room.getPrice(),
                    room.isBusy()
            });
        }
    }
    private void loadCustomersToTable() {
    DefaultTableModel model = (DefaultTableModel) CustomerTable.getModel();
    model.setRowCount(0);
    for (Customers c : customers.values()) {
        model.addRow(new Object[]{c.getId(), c.getName(), c.getPhone(), c.getEmail()});
    }
    }
    private void loadReservationsToTable() {
        DefaultTableModel model = (DefaultTableModel) ReservationTable.getModel();


        for (Reservation r : roomManger.getReservations().values()) {
            // قائمة الخدمات كـ String مفصولة بفاصلة
            String servicesStr = "";
            if (r.getServices() != null && !r.getServices().isEmpty()) {
                for (Service s : r.getServices()) {
                    servicesStr += s.getName() + ", ";
                }
                servicesStr = servicesStr.substring(0, servicesStr.length() - 2); // إزالة الفاصلة الأخيرة
            }

            model.addRow(new Object[]{
                    r.getReservationId(),
                    r.getRoom().getRoomId(),
                    r.getCustomer().getId(),
                    r.getCheckIn(),
                    r.getCheckOut(),
                    servicesStr
            });
        }
    }
    /**
     * Creates new form UserFram
     */
    public UserFram() {
        initComponents();

        // Initialize managers and load data in the correct order
        roomManger = new RoomServiceManager();
        userManager = new UserManager();

        // Load base data from files
        roomManger.loadRoomsFromFile();
        customers = userManager.getCustomers();
        roomManger.loadReservationsFromFile(customers);
        roomManger.loadServicesFromFile();

        // Get in-memory maps
        rooms = roomManger.getRooms();
        services = roomManger.getServices();

        // Populate tables and filters
        loadRoomsToTable();
        loadReservationsToTable();
        loadCustomersToTable();
        populateFiltersAndServices();
    }

    /**
     * Initialize room type / availability filters and services combo box
     * in a way consistent with the main admin frame logic.
     */
    private void populateFiltersAndServices() {

        TypeFilter.removeAllItems();
        TypeFilter.addItem("All");
        HashSet<String> seenTypes = new HashSet<>();
        for (Room room : rooms.values()) {
            String type = room.getRoomType();
            if (type != null && seenTypes.add(type)) {
                TypeFilter.addItem(type);
            }
        }

        // Populate busy/availability filter
        BusyFilter.removeAllItems();
        BusyFilter.addItem("All");
        BusyFilter.addItem("Available");
        BusyFilter.addItem("Busy");

        // Populate services combo box with service names
        ServiceBox.removeAllItems();
        for (Service s : services.values()) {
            ServiceBox.addItem(s.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RoomTap = new javax.swing.JTabbedPane();
        RoomPanel = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        GetCheckOuts = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Back = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        ReservationID = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        ServiceBox = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        ReservationTable = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        RoomID2 = new javax.swing.JTextField();
        CustomerId2 = new javax.swing.JTextField();
        Checkin = new javax.swing.JTextField();
        Checkout = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        RoomTable2 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        TypeFilter = new javax.swing.JComboBox<>();
        BusyFilter = new javax.swing.JComboBox<>();
        Applybtn = new javax.swing.JButton();
        RoomToGuest = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        CustomersPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CusId = new javax.swing.JTextField();
        CusName = new javax.swing.JTextField();
        CusPhone = new javax.swing.JTextField();
        CusEmail = new javax.swing.JTextField();
        Addcus = new javax.swing.JButton();
        Deletecus = new javax.swing.JButton();
        updatecus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CustomerTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GetCheckOuts.setText("get check outs");
        GetCheckOuts.addActionListener(this::GetCheckOutsActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reservation Id", "Room Id", "Customer Id", "Customer Name", "Check out date", "Days Until"
            }
        ));
        jScrollPane8.setViewportView(jTable1);

        Back.setText("Logout");
        Back.addActionListener(this::BackActionPerformed);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(GetCheckOuts, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(500, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Back))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(GetCheckOuts)
                .addGap(25, 25, 25)
                .addComponent(Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Near Checkouts", jPanel8);

        jLabel25.setText("Reservation Id");

        jLabel26.setText("Service");

        jButton2.setText("Add service to Reservation");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        ReservationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Room Id", "Customer Id", "Check in", "Check out", "Service"
            }
        ));
        jScrollPane7.setViewportView(ReservationTable);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(323, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addComponent(ReservationID, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(173, 173, 173)
                                .addComponent(ServiceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(352, 352, 352))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(402, 402, 402))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReservationID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(15, 15, 15)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ServiceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Room service", jPanel9);



        jLabel19.setText("Room Id");

        jLabel20.setText("Customer Id");

        jLabel21.setText("Check in (yyyy-mm-dd)");

        jLabel22.setText("check out (yyyy-mm-dd)");

        RoomTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Room Type", "Price", "Is Busy"
            }
        ));
        jScrollPane6.setViewportView(RoomTable2);

        jLabel23.setText("Filter by room type");

        jLabel24.setText("filter by Availabilitty");

        TypeFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));

        BusyFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));

        Applybtn.setText("Apply");
        Applybtn.addActionListener(this::ApplybtnActionPerformed);

        RoomToGuest.setText("Assing Room to Guest");
        RoomToGuest.addActionListener(this::RoomToGuestActionPerformed);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(Applybtn))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(TypeFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(BusyFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RoomToGuest)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(RoomID2)
                        .addComponent(CustomerId2)
                        .addComponent(Checkin)
                        .addComponent(Checkout, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)))
                .addGap(53, 53, 53))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RoomID2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(TypeFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustomerId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Checkin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel24)
                                .addComponent(BusyFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Checkout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(RoomToGuest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(Applybtn)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Reserve", jPanel7);

        jButton4.setText("Get Invoice");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jLabel27.setText("Reservation Id");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane9.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(315, Short.MAX_VALUE))
            .addComponent(jScrollPane9)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(467, 467, 467))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Invoice", jPanel10);

        javax.swing.GroupLayout RoomPanelLayout = new javax.swing.GroupLayout(RoomPanel);
        RoomPanel.setLayout(RoomPanelLayout);
        RoomPanelLayout.setHorizontalGroup(
            RoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        RoomPanelLayout.setVerticalGroup(
            RoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 889, Short.MAX_VALUE)
        );

        RoomTap.addTab("Room", RoomPanel);

        jLabel5.setText("Id");

        jLabel6.setText("Name");

        jLabel7.setText("phome");

        jLabel8.setText("Email");


        Addcus.setText("Add");
        Addcus.addActionListener(this::AddcusActionPerformed);

        Deletecus.setText("Delete");
        Deletecus.addActionListener(this::DeletecusActionPerformed);

        updatecus.setText("update");
        updatecus.addActionListener(this::updatecusActionPerformed);

        CustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Phone", "Email"
            }
        ));
        jScrollPane2.setViewportView(CustomerTable);

        javax.swing.GroupLayout CustomersPanelLayout = new javax.swing.GroupLayout(CustomersPanel);
        CustomersPanel.setLayout(CustomersPanelLayout);
        CustomersPanelLayout.setHorizontalGroup(
            CustomersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomersPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(CusPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CustomersPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CusEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomersPanelLayout.createSequentialGroup()
                        .addGroup(CustomersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CustomersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CusId)
                            .addComponent(CusName, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))))
                .addGap(395, 395, 395)
                .addGroup(CustomersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Addcus)
                    .addComponent(Deletecus)
                    .addComponent(updatecus))
                .addGap(353, 353, 353))
            .addComponent(jScrollPane2)
        );
        CustomersPanelLayout.setVerticalGroup(
            CustomersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomersPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(CustomersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CusId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Addcus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CustomersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deletecus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CustomersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CusPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatecus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CusEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE))
        );

        RoomTap.addTab("Customers", CustomersPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RoomTap)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RoomTap)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {
        LoginGui bac = new LoginGui();
        bac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void updatecusActionPerformed(java.awt.event.ActionEvent evt) {
        Integer id = null;
        int row = CustomerTable.getSelectedRow();
        if (row != -1) id = Integer.parseInt(CustomerTable.getValueAt(row, 0).toString());
        else if (!CusId.getText().isEmpty()) id = Integer.parseInt(CusId.getText());
        if (id == null || !customers.containsKey(id)) return;
        String name = CusName.getText();
        String phone = CusPhone.getText();
        String email = CusEmail.getText();
        if (name.isEmpty() || phone.isEmpty() || email.isEmpty()) return;
        customers.put(id, new Customers(id, name, phone, email));
        userManager.saveCustomersToFile();
        loadCustomersToTable();
    }                                         

    private void DeletecusActionPerformed(java.awt.event.ActionEvent evt) {
        Integer id = null;
        int row = CustomerTable.getSelectedRow();
        if (row != -1) id = Integer.parseInt(CustomerTable.getValueAt(row, 0).toString());
        else if (!CusId.getText().isEmpty()) id = Integer.parseInt(CusId.getText());
        if (id == null || !customers.containsKey(id)) return;
        int confirm = JOptionPane.showConfirmDialog(this,"Are you sure?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;
        customers.remove(id);
        userManager.saveCustomersToFile();

        loadCustomersToTable();
    }                                         

    private void AddcusActionPerformed(java.awt.event.ActionEvent evt) {
        try{int id = Integer.parseInt(CusId.getText());
        String name = CusName.getText();
        String phone = CusPhone.getText();
        String email = CusEmail.getText();
        customers.put(id, new Customers(id, name, phone, email));
        loadCustomersToTable();
        userManager.saveCustomersToFile();} catch (Exception e) {JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }                                      

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {

        int resId;
        try {
            resId = Integer.parseInt(jTextField1.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid Reservation ID");
            return;
        }

        Reservation r = roomManger.getReservations().get(resId);
        if (r == null) {
            JOptionPane.showMessageDialog(this, "Reservation not found");
            return;
        }

        long days = java.time.temporal.ChronoUnit.DAYS.between(
            r.getCheckIn(), r.getCheckOut()
        );

        double roomPrice = r.getRoom().getPrice();
        double roomTotal = roomPrice * days;

        double servicesTotal = 0;
        if (r.getServices() != null) {
            for (Service s : r.getServices()) {
                servicesTotal += s.getPrice();
            }
        }

        double total = roomTotal + servicesTotal;

        String invoice =
        "Invoice\n" +
        "-----------------------\n" +
        "Reservation ID: " + r.getReservationId() + "\n" +
        "Customer: " + r.getCustomer().getName() + "\n" +
        "Room ID: " + r.getRoom().getRoomId() + "\n" +
        "Days: " + days + "\n" +
        "Room Total: " + roomTotal + "\n" +
        "Services Total: " + servicesTotal + "\n" +
        "-----------------------\n" +
        "TOTAL: " + total;

        JOptionPane.showMessageDialog(this, invoice);
    }                                        

    private void RoomToGuestActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int roomId = Integer.parseInt(RoomID2.getText());
            int customerId = Integer.parseInt(CustomerId2.getText());
            // Enforce yyyy-MM-dd date format
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDate checkIn;
            LocalDate checkOut;
            try {
                checkIn = LocalDate.parse(Checkin.getText().trim(), formatter);
                checkOut = LocalDate.parse(Checkout.getText().trim(), formatter);
            } catch (DateTimeParseException e) {
                JOptionPane.showMessageDialog(this,
                        "Invalid date format. Please use yyyy-MM-dd (e.g. 2025-01-31).",
                        "Invalid Date",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            Customers customer = customers.get(customerId);
            if (customer == null) {
                JOptionPane.showMessageDialog(this, "Customer not found");
                return;
            }

            boolean success = roomManger.assignRoomToGuest(roomId, customer, checkIn, checkOut);

            if (success) {
                JOptionPane.showMessageDialog(this, "Room assigned successfully!");
                loadRoomsToTable();

            } else {
                JOptionPane.showMessageDialog(this, "Room is not available or invalid!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid input: " + e.getMessage());
        }
    }                                           

    private void ApplybtnActionPerformed(java.awt.event.ActionEvent evt) {
        String roomType = TypeFilter.getSelectedItem().toString();
        if(roomType.equals("All")) roomType = null;

        String status = BusyFilter.getSelectedItem().toString();
        Boolean isBusy = null; // null = كل الغرف
        if(status.equals("Available")) isBusy = false;
        else if(status.equals("Busy")) isBusy = true;

        ArrayList<Room> filteredRooms = roomManger.filterRooms(roomType, isBusy, null);

        DefaultTableModel model = (DefaultTableModel) RoomTable2.getModel();
        model.setRowCount(0);
        for(Room r : filteredRooms) {
            model.addRow(new Object[]{r.getRoomId(), r.getRoomType(), r.getPrice(), r.isBusy()});
        }
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        try {

            int resId = Integer.parseInt(ReservationID.getText());
            Reservation res = roomManger.getReservations().get(resId);

            if (res == null) {
                JOptionPane.showMessageDialog(this, "Reservation not found");
                return;
            }

            // 2. جلب الخدمة المختارة من ComboBox (by name)
            String selectedName = (String) ServiceBox.getSelectedItem();
            if (selectedName == null || selectedName.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Select a service");
                return;
            }

            Service selectedService = null;
            for (Service s : services.values()) {
                if (selectedName.equals(s.getName())) {
                    selectedService = s;
                    break;
                }
            }
            if (selectedService == null) {
                JOptionPane.showMessageDialog(this, "Selected service not found");
                return;
            }

            // 3. إضافة الخدمة للحجز
            if (!res.getServices().contains(selectedService)) {
                res.getServices().add(selectedService);
                roomManger.updateReservation(resId, res); // حفظ التغيير في الملفات
            } else {
                JOptionPane.showMessageDialog(this, "Service already assigned");
            }

            // 4. تحديث الجدول
            loadReservationsToTable();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter a valid Reservation ID");
        }
    }                                        

    private void GetCheckOutsActionPerformed(java.awt.event.ActionEvent evt) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        LocalDate now = LocalDate.now();
        


        for (Reservation r : roomManger.getReservations().values()) {
            int reservationId = r.getReservationId();
            int roomId = r.getRoom().getRoomId();
            int customerId = r.getCustomer().getId();
            String customerName = r.getCustomer().getName();
            LocalDate checkOutDate = r.getCheckOut();
            LocalDate checkInDate = r.getCheckIn();
            long daysUntil = java.time.temporal.ChronoUnit.DAYS.between(now ,checkOutDate );

            model.addRow(new Object[]{
                reservationId,
                roomId,
                customerId,
                customerName,
                checkOutDate,
                daysUntil
            });
        }
    }                                            

    private javax.swing.JButton Addcus;
    private javax.swing.JButton Applybtn;
    private javax.swing.JButton Back;
    private javax.swing.JComboBox<String> BusyFilter;
    private javax.swing.JTextField Checkin;
    private javax.swing.JTextField Checkout;
    private javax.swing.JTextField CusEmail;
    private javax.swing.JTextField CusId;
    private javax.swing.JTextField CusName;
    private javax.swing.JTextField CusPhone;
    private javax.swing.JTextField CustomerId2;
    private javax.swing.JTable CustomerTable;
    private javax.swing.JPanel CustomersPanel;
    private javax.swing.JButton Deletecus;
    private javax.swing.JButton GetCheckOuts;
    private javax.swing.JTextField ReservationID;
    private javax.swing.JTable ReservationTable;
    private javax.swing.JTextField RoomID2;
    private javax.swing.JPanel RoomPanel;
    private javax.swing.JTable RoomTable2;
    private javax.swing.JTabbedPane RoomTap;
    private javax.swing.JButton RoomToGuest;
    private javax.swing.JComboBox<String> ServiceBox;
    private javax.swing.JComboBox<String> TypeFilter;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton updatecus;
}